apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/petclinic"
  SPRING_DATASOURCE_USERNAME: "petclinic"
  SPRING_DATASOURCE_PASSWORD: "petclinic"