namespace: petclinic-dev # Default namespace for development

config_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-config-server
  tag: latest
  port: 8888
  resources:
    limits:
      memory: 512Mi

discovery_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-discovery-server
  tag: latest
  port: 8761
  resources:
    limits:
      memory: 512Mi
  env:
    SPRING_PROFILES_ACTIVE: docker,kubernetes
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
    spring.cloud.config.uri: http://10.108.42.224:8888