namespace: petclinic-dev # Default namespace for development

config_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-config-server
  tag: latest
  port: 8888
  resources:
    limits:
      memory: 512Mi

discovery_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-discovery-server
  tag: latest
  port: 8761
  resources:
    limits:
      memory: 512Mi
  env:
    SPRING_PROFILES_ACTIVE: docker
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"

customers_service:
  replicaCount: 1
  image: springcommunity/spring-petclinic-customers-service
  tag: latest
  port: 8081
  resources:
    limits:
      memory: 512Mi
  env:
    SPRING_PROFILES_ACTIVE: docker
    SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
    SPRING_CLOUD_DISCOVERY_HEALTH_TIMEOUT: "5000"
    SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_USE-DISCOVERY-METADATA: "true"
    SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_MANAGEMENT_PORT: "${management.server.port:${server.port}}"
    SPRING_CLOUD_DISCOVERY_HEALTH_RETRY_MAX_ATTEMPTS: "5"
    SPRING_CLOUD_DISCOVERY_HEALTH_RETRY_INITIAL_INTERVAL: "1000"

visits_service:
  replicaCount: 1
  image: springcommunity/spring-petclinic-visits-service
  tag: latest
  port: 8082
  resources:
    limits:
      memory: 512Mi
  env:
    SPRING_PROFILES_ACTIVE: docker
    SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
    SPRING_CLOUD_DISCOVERY_HEALTH_TIMEOUT: "5000"
    SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_USE-DISCOVERY-METADATA: "true"
    SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_MANAGEMENT_PORT: "${management.server.port:${server.port}}"
    SPRING_CLOUD_DISCOVERY_HEALTH_RETRY_MAX_ATTEMPTS: "5"
    SPRING_CLOUD_DISCOVERY_HEALTH_RETRY_INITIAL_INTERVAL: "1000"