namespace: petclinic

config_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-config-server
  tag: latest
  port: 8888
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 100m
