namespace: petclinic-dev

config_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-config-server
  tag: latest
  port: 8888
  resources:
    limits:
      memory: 512Mi

discovery_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-discovery-server
  tag: latest
  port: 8761
  resources:
    limits:
      memory: 512Mi
  env:
    SPRING_PROFILES_ACTIVE: docker
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"