namespace: petclinic-dev # Default namespace for development

config_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-config-server
  tag: latest
  port: 8888
  resources:
    limits:
      memory: 512Mi

discovery_server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-discovery-server
  tag: latest
  port: 8761
  resources:
    limits:
      memory: 512Mi
  env:
    SPRING_PROFILES_ACTIVE: docker # Keep this, as it's part of the app's expected setup
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
    # THIS IS THE CRUCIAL CHANGE: Override the hardcoded config server URL
    SPRING_CONFIG_IMPORT: configserver:http://petclinic-dev-config-server-svc:8888