namespace: petclinic

components:
  config-server: true

config-server:
  replicaCount: 1
  image: springcommunity/spring-petclinic-config-server
  tag: latest
  port: 8888
  resources:
    limits:
      memory: 512Mi