# config file version
apiVersion: 1

# list of datasources to insert/update depending what's available in the database
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  org_id: 1
  url: http://prometheus.petclinic-prod.svc.cluster.local:9090
  is_default: true
  version: 1
  editable: true

- name: Loki
  type: loki
  access: proxy
  org_id: 1
  url: http://loki-stack.petclinic-prod.svc.cluster.local:3100
  is_default: false
  editable: true