namespace: Petclinic

config_server:
  image: springcommunity/spring-petclinic-config-server:latest

discovery_server:
  image: springcommunity/spring-petclinic-discovery-server:latest

customers_service:
  image: springcommunity/spring-petclinic-customers-service:latest

visits_service:
  image: springcommunity/spring-petclinic-visits-service:latest

vets_service:
  image: springcommunity/spring-petclinic-vets-service:latest

api_gateway:
  image: springcommunity/spring-petclinic-api-gateway:latest

tracing_server:
  image: openzipkin/zipkin:latest
  # serviceType: LoadBalancer 
  # nodePort: 31414

admin_server:
  image: springcommunity/spring-petclinic-admin-server:latest
  # serviceType: LoadBalancer 
  # nodePort: 30092

grafana:
  enabled: true
  image: grafana/grafana:latest
  service:
    port: 3030

prometheus:
  enabled: true
  image: prom/prometheus:latest
  service:
    port: 9091
    targetPort: 9090