apiVersion: v2
name: monitoring
version: 0.1.0
dependencies:
  - name: prometheus
    version: 25.21.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 7.3.9
    repository: https://grafana.github.io/helm-charts
  - name: loki-stack
    version: 2.9.10
    repository: https://grafana.github.io/helm-charts
