apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-server
  namespace: {{ .Values.namespace }}
  labels:
    app: admin-server
    app.kubernetes.io/name: admin-server
    app.kubernetes.io/instance: {{ .Release.Name }}-admin-server
spec:
  replicas: {{ .Values.admin_server.replicaCount }}
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: "{{ .Values.admin_server.image }}:{{ .Values.admin_server.tag }}"
          ports:
            - containerPort: {{ .Values.admin_server.port }}
          resources:
            {{- toYaml .Values.admin_server.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.admin_server.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.admin_server.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-server-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: {{ .Values.admin_server.port }}
      targetPort: {{ .Values.admin_server.port }}
    {{- if .Values.admin_server.nodePort }}
    nodePort: {{ .Values.admin_server.nodePort }}
    {{- end }}
  type: {{ .Values.admin_server.serviceType | default "LoadBalancer" }}