apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}-api-gateway
spec:
  replicas: {{ .Values.api_gateway.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.api_gateway.image }}:{{ .Values.api_gateway.tag }}"
          ports:
            - containerPort: {{ .Values.api_gateway.port }}
          resources:
            {{- toYaml .Values.api_gateway.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.api_gateway.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.api_gateway.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: {{ .Values.api_gateway.port }}
      targetPort: {{ .Values.api_gateway.port }}