apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
        - name: tracing-server
          image: {{ .Values.tracingserver.image | default "openzipkin/zipkin" }}
          ports:
            - containerPort: 9411
          resources:
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9411
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: tracing-server
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 31411 # Optional: Expose externally
  type: LoadBalancer # Or NodePort