apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hao-assignments/devops-lab02-kubernetes.git
    path: charts/monitoring
    targetRevision: HEAD
    # helm:
      # valueFiles:
        # - environments/prod/monitoring-values.yaml  # tùy môi trường
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
